Remove deprecated targetCommitAndReturnError
Conflicts with the non-deprecated method in Swift 2 (Xcode 7b6)

error: ambiguous use of 'targetCommit()'
                    let gt_commit = try! gt_branch.targetCommit()
                                         ^
ObjectiveGit.GTBranch:38:14: note: found this candidate
  @objc func targetCommit() throws -> GTCommit
             ^
ObjectiveGit.GTBranch:86:14: note: found this candidate
  @objc func targetCommit() throws -> GTCommit